networking_init_cms_default:
    path: /
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::homeAction}

networking_init_cms_home:
    path: /
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::homeAction}

networking_init_cms_admin:
    path: /admin/
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::adminAction}

networking_init_cms_admin_security_login:
    path: /admin/login
    defaults: { _controller: Networking\InitCmsBundle\Controller\AdminSecurityController::loginAction}

networking_init_cms_admin_security_check:
    path: /admin/login_check
    defaults: { _controller: Networking\InitCmsBundle\Controller\AdminSecurityController::checkAction}
    methods: [POST]

networking_init_cms_admin_security_logout:
    path: /admin/logout
    defaults: { _controller: Networking\InitCmsBundle\Controller\AdminSecurityController::logoutAction}

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin

networking_init_change_admin_language:
    path: /change_admin_language/{locale}
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::changeAdminLanguageAction}
    methods: [GET|POST]
    requirements:
        locale: .+

networking_init_change_language:
    path: /change_language/{oldLocale}/{locale}
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::changeLanguageAction}
    methods: [GET|POST]
    requirements:
        locale: .+

networking_init_view_draft:
    path: /view_draft/{locale}/{path}
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::viewDraftAction}
    requirements:
        locale: (.*)?
        path: (.*)?

networking_init_view_draft_no_param:
    path: /view_draft
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::viewDraftAction}

networking_init_view_live:
    path: /view_live/{locale}/{path}
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::viewLiveAction}
    requirements:
        locale: (.*)?
        path: (.*)?

networking_init_view_live_no_param:
    path: /view_live
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::viewLiveAction}

networking_init_cms_help:
    path: /admin/help/{adminCode}/{action}
    defaults: {_controller: Networking\InitCmsBundle\Controller\HelpTextController::adminHelpAction}
    requirements:
        adminCode: .+
        action: (.*)?

networking_init_cms_help_dashboard:
    path: /admin/help/{adminCode}
    defaults: {_controller: Networking\InitCmsBundle\Controller\HelpTextController::adminHelpAction}
    requirements:
        adminCode: .+

networking_init_cms_file_download:
    path: /file/download/{id}/{name}
    defaults: { _controller: Sonata\MediaBundle\Controller\MediaController::downloadAction, format: 'reference' }
    requirements:
        name: (.*)?
        format: (.*)?

networking_init_cms_image_view:
    path: /image/view/{id}/{format}/{name}
    defaults: { _controller: Networking\InitCmsBundle\Controller\MediaController::viewImageAction, format: 'reference' }
    requirements:
        name: (.*)?
        format: (.*)?

networking_init_cms_clear_cache:
    path: /cache/clear
    defaults: { _controller: Networking\InitCmsBundle\Controller\CacheController::clearAction}

initcms_no_translation:
    path: /no_translation
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::translationNotFoundAction}

initcms_404:
    path: /404
    defaults: {_controller: Networking\InitCmsBundle\Controller\FrontendPageController::pageNotFoundAction}

xml_sitemap:
    path: /xml_sitemap/{locale}
    defaults: {_controller: Networking\InitCmsBundle\Controller\XmlController::siteMapAction, locale: ''}
    requirements:
    methods: GET



_initcms_admin_navbar:
    path: '/admin/_initcms_admin_navbar/{page_id}'
    defaults: { _controller: Networking\InitCmsBundle\Controller\FrontendPageController::adminNavbarAction}

networking_init_cms_set_admin_portal_width:
    path: /admin/set_admin_portal_width
    defaults: { _controller: Networking\InitCmsBundle\Controller\CmsHelperController::setAdminPortalWidthAction}

networking_init_cms_admin_login:
    path: /admin/login{trailingSlash}
    defaults:
      _controller: FrameworkBundle:Redirect:urlRedirect
      path: /admin/
      permanent: true
    requirements: { trailingSlash : "[/]{1}" }


networking_init_cms_page_url_json:
    path: /cms/pages/internal-url.json
    defaults: { _controller: Networking\InitCmsBundle\Controller\FrontendPageController::getJsonUrlsAction}


