NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/cms.yaml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

oneup_uploader:
    resource: .
    type: uploader

networking_init_cms_maintenance:
    controller: Networking\InitCmsBundle\Action\MaintenanceAction
    path:   /maintenance.html

when@dev:
    networking_init_cms_maintenance_debug:
        controller: Networking\InitCmsBundle\Action\MaintenanceAction
        path:   /_debug/maintenance.html



