NetworkingInitCmsBundle:
    resource: "@NetworkingInitCmsBundle/Resources/config/routing/cms.yaml"
    prefix:   /

# Lexik Translation bundle

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translation


# Sonata-project Bundles
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin


media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

oneup_uploader:
    resource: .
    type: uploader


