<?php

declare(strict_types=1);

/**
 * This file is part of the init_cms_sandbox package.
 *
 * (c) net working AG <info@networking.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Networking\InitCmsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Networking\InitCmsBundle\Model\UserInterface;
use Sonata\UserBundle\Entity\BaseUser as SonataBaseUser;
use Networking\InitCmsBundle\Model\AdminSettings;

/**
 * @author Yorkie Chadwick <y.chadwick@networking.ch>
 */
abstract class BaseUser extends SonataBaseUser implements UserInterface
{
    /**
     * @var int
     */
    protected $id;

    /**
     * @var \Networking\InitCmsBundle\Model\AdminSettings
     */
    protected $adminSettings;

    /**
     * @var \DateTime
     */
    protected ?DateTime $lastActivity = null;

    protected ?string $twoStepVerificationCode = null;

    /**
     * @var Group[]|Collection
     */
    protected Collection|array $groups;

    protected ?string $firstname = null;

    protected ?string $lastname = null;


    protected ?string $locale = null;

    public function getHexId()
    {
        return bin2hex('user_'.$this->getId());
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale)
    {
        $this->locale = $locale;
        return $this;
    }

    /**
     * Hook on pre-persist operations.
     */
    public function prePersist(): void
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }

    /**
     * Hook on pre-update operations.
     */
    public function preUpdate(): void
    {
        $this->updatedAt = new \DateTime();
    }

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return array
     */
    public function getAdminSettings(): array
    {

        return $this->adminSettings ?? [];
    }

    /**
     * @param $key
     *
     * @return mixed
     */
    public function getAdminSetting($key): mixed
    {
        if (array_key_exists($key, $this->getAdminSettings())) {
            return $this->adminSettings[$key];
        }

        return false;
    }

    /**
     * @param $key
     * @param $value
     */
    public function setAdminSetting($key, $value): void
    {
        if (!$this->adminSettings) {
            $this->adminSettings = [];
        }

        $this->adminSettings[$key] = $value;
    }

    /**
     * @return mixed
     */
    public function getTwoStepVerificationCode(): ?string
    {
        return $this->twoStepVerificationCode;
    }

    /**
     * @return BaseUser
     */
    public function setTwoStepVerificationCode(?string $twoStepVerificationCode): self
    {
        $this->twoStepVerificationCode = $twoStepVerificationCode;

        return $this;
    }


    public function getHash(): string
    {
        return md5(strtolower(trim($this->email)));
    }

    /**
     * @param \DateTime $lastActivity
     */
    public function setLastActivity($lastActivity): void
    {
        $this->updatedAt = $lastActivity;
    }

    /**
     * @return \DateTime
     */
    public function getLastActivity(): ?\DateTime
    {
        return $this->updatedAt;
    }

    public function getRoles(): array
    {
        $roles = parent::getRoles(); // TODO: Change the autogenerated stub

        foreach ($this->getGroups() as $group) {
            $roles = array_merge($roles, $group->getRoles());
        }

        return array_values(array_unique($roles));
    }


    /**
     * @return BaseUser
     */
    public function setGroups(mixed $groups): self
    {
        foreach ($groups as $group) {
            $this->addGroup($group);
        }

        return $this;
    }


    /**
     * {@inheritdoc}
     */
    public function getGroups(): Collection|array
    {
        return $this->groups ?: $this->groups = new ArrayCollection();
    }

    /**
     * {@inheritdoc}
     */
    public function getGroupNames(): array
    {
        $names = [];
        foreach ($this->getGroups() as $group) {
            $names[] = $group->getName();
        }

        return $names;
    }

    /**
     * {@inheritdoc}
     */
    public function hasGroup($name): bool
    {
        return in_array($name, $this->getGroupNames());
    }

    /**
     * {@inheritdoc}
     */
    public function addGroup(Group $group): self
    {
        if (!$this->getGroups()->contains($group)) {
            $this->getGroups()->add($group);
        }

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function removeGroup(Group $group): self
    {
        if ($this->getGroups()->contains($group)) {
            $this->getGroups()->removeElement($group);
        }

        return $this;
    }


    /**
     * {@inheritdoc}
     */
    public function setFirstname($firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }


    /**
     * {@inheritdoc}
     */
    public function setLastname($lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getLastname(): ?string
    {
        return $this->lastname;
    }


    /**
     * {@inheritdoc}
     */
    public function getFullname(): string
    {
        if (!$this->getFirstname() && !$this->getLastname()) {
            return $this->getUsername();
        }

        return sprintf('%s %s', $this->getFirstname(), $this->getLastname());
    }

    public function hasStepVerificationCode(): bool
    {
        return !!$this->twoStepVerificationCode;
    }

    public function getDisplayName(): string
    {
        return $this->getFullname();
    }

}
