<?php

declare(strict_types=1);

/**
 * This file is part of the Networking package.
 *
 * (c) net working AG <info@networking.ch>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Networking\InitCmsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gaufrette\Util;
use Imagine\Image\Box;
use Networking\InitCmsBundle\Model\IgnoreRevertInterface;
use Sonata\MediaBundle\Entity\BaseMedia;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Attribute\Ignore;

/**
 * Class Media.
 *
 * @author Yorkie Chadwick <y.chadwick@networking.ch>
 */
#[ORM\Entity]
#[ORM\Table(name: 'media__media')]
#[ORM\HasLifecycleCallbacks]
class Media extends BaseMedia implements IgnoreRevertInterface
{
    /**
     * @var int
     */
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    protected ?int $id = null;

    #[ORM\ManyToMany(targetEntity: 'Networking\InitCmsBundle\Entity\Tag')]
    #[ORM\JoinTable(name: 'media_tags')]
    #[ORM\JoinColumn(name: 'media_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'tag_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[Ignore]
    protected Collection $tags;

    #[ORM\Column(name: 'locale', type: 'string', length: 6, nullable: true)]
    protected ?string $locale = null;

    #[ORM\Column(name: 'md5_file', type: 'string', length: 255, nullable: true)]
    protected ?string $md5File = null;

    #[Ignore]
    public function getGalleryItems(): Collection
    {
        return parent::getGalleryItems(); // TODO: Change the autogenerated stub
    }

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        parent::__construct();
    }

    #[Ignore]
    public function setBinaryContent($binaryContent): void
    {
        $this->previousProviderReference = $this->providerReference;
        $this->providerReference = null;
        $this->binaryContent = $binaryContent;
        $checksum = $this->getChecksum();
        $this->setMd5File($checksum);
    }

    public function addTags(Tag $tag): static
    {
        $this->tags->add($tag);

        return $this;
    }

    public function getTags()
    {
        return $this->tags;
    }

    public function setTags(?ArrayCollection $tags = null): static
    {
        $this->tags = $tags;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale = null): static
    {
        $this->locale = $locale;

        return $this;
    }

    public function getImage(): int
    {
        return $this->getId();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function setImage($image): static
    {
        return $this;
    }

    public function getMd5File(): ?string
    {
        return $this->md5File;
    }

    public function setMd5File(?string $md5File = null): void
    {
        $this->md5File = $md5File;
    }

    public function getChecksum(): ?string
    {
        if (!$this->binaryContent) {
            return $this->md5File;
        }

        if ($this->getBinaryContent() instanceof UploadedFile) {
            return Util\Checksum::fromFile(
                $this->getBinaryContent()->getPathName()
            );
        }

        return Util\Checksum::fromContent($this->getBinaryContent());
    }

    /**
     * @return $this
     */
    public function getSelf(): static
    {
        return $this;
    }

    #[ORM\PrePersist]
    public function prePersist(): void
    {
        $checksum = $this->getChecksum();
        $this->setMd5File($checksum);

        parent::prePersist();
    }

    #[ORM\PreUpdate]
    public function preUpdate(): void
    {
        $checksum = $this->getChecksum();
        $this->setMd5File($checksum);

        parent::preUpdate();
    }

    #[Ignore]
    public function getBox(): Box
    {
        return parent::getBox();
    }
}
