doctrine:
    dbal:
        types:
#            phone_number: "Misd\\PhoneNumberBundle\\Doctrine\\DBAL\\Types\\PhoneNumberType"
#            json: "Doctrine\\DBAL\\Types\\JsonType"
        default_connection: default
        connections:
            default:
                driver: '%env(DATABASE_DRIVER)%'
                server_version: '5.7'
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                mapping_types:
                    enum: string
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping:     true
                connection:       default
                filters:
                    softdeleteable:
                        class: "Gedmo\\SoftDeleteable\\Filter\\SoftDeleteableFilter"
                        enabled: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    gedmo_translatable:
                        type: attribute
                        prefix: "Gedmo\\Translatable\\Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: attribute
                        prefix: "Gedmo\\Translator\\Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: attribute
                        prefix: "Gedmo\\Loggable\\Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: attribute
                        prefix: "Gedmo\\Tree\\Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_sortable:
                        type: attribute
                        prefix: "Gedmo\\Sortable\\Entity"
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Sortable/Entity"
                        alias: GedmoSortable # this one is optional and will default to the name set for the mapping
                        is_bundle: false

