# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.cache_dir%/flysystem'
        media:
            local:
                location: "%kernel.project_dir%/public/"
        cache:
            local:
                location: "%kernel.project_dir%/public/media/cache/"
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
        media:
            adapter: media
        cache:
            adapter: cache
