sonata_user:
    security_acl: false
    impersonating:
        route:                networking_init_cms_admin
        parameters:           { path: /}
    class:
        user: 'App\Entity\User'

    resetting:
        email:
            address: initcms@localhost
            sender_name: InitCms

    admin:                  # Admin Classes
        user:
            class:          'Networking\InitCmsBundle\Admin\Entity\UserAdmin'
            controller:     'NetworkingInitCmsBundle:CRUD'
            translation:    'SonataUserBundle'
