cmf_routing:
    chain:
         routers_by_id:
            router.default: 300 #called first
            networking_init_cms.cms_router: 100 #called second
    dynamic:
         route_provider_service_id: networking_init_cms.content_route_manager
         controllers_by_class:
            Networking\InitCmsBundle\Model\Page: Networking\InitCmsBundle\Controller\FrontendPageController::indexAction
            Networking\InitCmsBundle\Model\PageSnapshot: Networking\InitCmsBundle\Controller\FrontendPageController::indexAction
         content_repository_service_id: networking_init_cms.page_manager
