# Please see the following page for more information: https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way#configuration

webauthn:
    credential_repository: 'Networking\InitCmsBundle\Repository\WebauthnCredentialRepository' # CREATE YOUR REPOSITORY AND CHANGE THIS!
    user_repository: 'Networking\InitCmsBundle\Repository\WebauthnUserEntityRepository' # CREATE YOUR REPOSITORY AND CHANGE THIS!
    controllers:
        enabled: true
    creation_profiles:
        default:
            public_key_credential_parameters:
                - !php/const Cose\Algorithms::COSE_ALGORITHM_ES256
                - !php/const Cose\Algorithms::COSE_ALGORITHM_EDDSA
                - !php/const Cose\Algorithms::COSE_ALGORITHM_RS256
            authenticator_selection_criteria:
                attachment_mode: !php/const Webauthn\AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM
            rp:
                name: '%env(RELYING_PARTY_NAME)%' # Please adapt the env file with the correct relaying party ID or set null
                id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
    request_profiles:
        default:
            rp_id: '%env(RELYING_PARTY_ID)%' # Please adapt the env file with the correct relaying party ID or set null
