Networking\InitCmsBundle\Entity\Media:
    properties:
        id:
            type: integer
        locale:
            type: string
        tags:
            exclude: true
        galleryHasMedias:
            exclude: true
        md5File:
            exclude: true

