Sonata\MediaBundle\Model\GalleryItem:
    properties:
        media:
            type: Networking\InitCmsBundle\Entity\Media
        position:
            type: integer
        updatedAt:
            type: DateTime
        createdAt:
            type: DateTime
        enabled:
            type: boolean
        gallery:
            type: Networking\InitCmsBundle\Entity\Gallery
