Sonata\MediaBundle\Model\Gallery:
    properties:
      context:
          type: string
      name:
          type: string
      enabled:
          type: boolean
      updatedAt:
          type: DateTime
      createdAt:
          type: DateTime
      defaultFormat:
          type: string
      galleryItems:
          type: ArrayCollection<Networking\InitCmsBundle\Entity\GalleryItem>
