Networking\InitCmsBundle\Entity\MenuItem:
    type: entity
    table: cms_menu
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        children:
            targetEntity: Networking\InitCmsBundle\Entity\MenuItem
            mappedBy: parent
            orderByField:
                lft:
                    direction: asc
    manyToOne:
        parent:
            targetEntity: Networking\InitCmsBundle\Entity\MenuItem
            inversedBy: children
            gedmo:
                0: treeParent
            joinColumn:
                name: parent_id
                referenced-column-name: id
                onDelete: 'SET NULL'